# permissions for end users to view kryptons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krypton-viewer-role
rules:
- apiGroups:
  - qingcloud.com.qingcloud.com
  resources:
  - kryptons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qingcloud.com.qingcloud.com
  resources:
  - kryptons/status
  verbs:
  - get
